server:
  address: 127.0.0.1
  port: 8090
  servlet:
    session:
      cookie:
        http-only: false
spring:
  # 静态资源配置
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations:
      # 自定义的系统材料存储路径
        - file:C:/Users/AITIAN/Desktop/
  profiles:
    active: druid
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: xxxxxx
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 邮件配置
  mail:
    # 默认的邮件编码为UTF-8
    default-encoding: utf-8
    # 配置SMTP服务器地址
    host: smtp.qq.com
    # 用户名邮箱账号
    username: "你的邮箱"
    # 授权码
    password: "你的邮箱授权码"
    # 配置SSL 加密工厂
    #以下可以配置或者不配置
    properties:
      mail:
        smtp:
          # 465 smt-ps 587 smtp
          port: 587
          auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  config: classpath:logback-spring.xml
# PageHelper
page helper:
  helperDialect: mysql
  reasonable: true  #开启合理化：页码<=0 查询第一页，页码>=总页数查询最后一页
  supportMethodsArguments: true
  params: count=countSql

# mybatis plus
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 259200
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否输出操作日志
  is-log: false
# 你在支付宝申请支付的相关参数
alipay:
  gateway: https://openapi.alipaydev.com/gateway.do
  appId: xxxxxx
  appPrivateKey: xxxxxx
  alipayPublicKey: xxxxxx
  # 自定义异步通知地址
  notifyUrl: http://xxxxxx/alipay/notify
  # 设置同步回调地址
  returnUrl: http://localhost/payed
springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true
    swagger:
      v2:
        enabled: true
# mail properties 配置
mail:
  from: "xxxxxx"
# 自定义系统材料传输存储路径需要与上面相同
# file transfer properties配置 (最后不加的分隔符 /)
transfer:
  # 头像存储路径
  avatar-home: "C:/Users/AITIAN/Desktop/avatars"
  # 商品图片存储路径
  product-image-home: "C:/Users/AITIAN/Desktop/image"